// Post-processes the `expo export --platform web` output into an installable,
// offline-capable PWA suitable for GitHub Pages project hosting.
//
// Expo's Metro web export emits only index.html + the JS bundle. This script
// adds: a web manifest, a service worker (full precache for offline), apple
// touch-icon + standalone meta tags, a .nojekyll marker (so Pages serves the
// underscore-prefixed _expo/ dir), and a 404.html SPA fallback.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

// Keep the base path in sync with app.json's experiments.baseUrl.
const appJson = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));
const BASE = (appJson.expo?.experiments?.baseUrl ?? '').replace(/\/$/, ''); // e.g. "/rogue"
const withBase = (p) => `${BASE}/${p.replace(/^\//, '')}`;

if (!fs.existsSync(dist)) {
  console.error('dist/ not found — run `expo export --platform web` first.');
  process.exit(1);
}

// --- icon: reuse the app icon for the home-screen/install icon ---------------
const iconSrc = path.join(root, 'assets', 'icon.png');
if (fs.existsSync(iconSrc)) fs.copyFileSync(iconSrc, path.join(dist, 'icon.png'));

// --- web manifest ------------------------------------------------------------
const manifest = {
  name: 'Rogue',
  short_name: 'Rogue',
  description: 'A classic roguelike — retrieve the Amulet of Yendor.',
  start_url: withBase('/'),
  scope: withBase('/'),
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#0a0a0a',
  theme_color: '#0a0a0a',
  icons: [
    { src: withBase('/icon.png'), sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: withBase('/icon.png'), sizes: '1024x1024', type: 'image/png', purpose: 'maskable' },
  ],
};
fs.writeFileSync(path.join(dist, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));

// --- service worker: precache every emitted file for offline play ------------
function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}
const precache = walk(dist)
  .map((f) => withBase('/' + path.relative(dist, f).split(path.sep).join('/')))
  .filter((url) => !url.endsWith('/sw.js'));
// Make sure the app entry (start_url) is cached so offline launch resolves,
// along with the SW registration stub written later in this script.
precache.push(withBase('/'));
precache.push(withBase('/sw-register.js'));

const CACHE = `rogue-pwa-${Date.now()}`;
const sw = `// Auto-generated by scripts/build-pwa.mjs — do not edit.
const CACHE = '${CACHE}';
const PRECACHE = ${JSON.stringify([...new Set(precache)], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const req = e.request;

  // Network-first for page navigations so a fresh deploy shows on the next
  // launch (no "open twice" dance); fall back to the cached shell offline.
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then((hit) => hit || caches.match('${withBase('/')}'))),
    );
    return;
  }

  // Cache-first for everything else — the JS bundles are content-hashed, so a
  // new build emits new filenames that never collide with stale cache entries.
  e.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      return fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match('${withBase('/')}'));
    }),
  );
});
`;
fs.writeFileSync(path.join(dist, 'sw.js'), sw);

// --- inject head tags + SW registration into index.html ----------------------
const indexPath = path.join(dist, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');

// Content-Security-Policy: the game is fully self-contained, so lock every
// source to same-origin (styles need 'unsafe-inline' — react-native-web
// injects its stylesheet at runtime). Defense-in-depth for a static PWA.
const csp = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join('; ');

const head = `
    <meta http-equiv="Content-Security-Policy" content="${csp}" />
    <link rel="manifest" href="${withBase('/manifest.webmanifest')}" />
    <meta name="theme-color" content="#0a0a0a" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="Rogue" />
    <link rel="apple-touch-icon" href="${withBase('/icon.png')}" />
  `;
if (!html.includes('rel="manifest"')) html = html.replace('</head>', `${head}</head>`);
html = html.replace(/<title>.*?<\/title>/, '<title>Rogue</title>');

// SW registration lives in an external file so script-src stays 'self'.
fs.writeFileSync(
  path.join(dist, 'sw-register.js'),
  `if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('${withBase('/sw.js')}', { scope: '${withBase('/')}' }).catch(function () {});
  });
}
`,
);
const reg = `
    <script src="${withBase('/sw-register.js')}" defer></script>
  `;
if (!html.includes('sw-register.js')) html = html.replace('</body>', `${reg}</body>`);
fs.writeFileSync(indexPath, html);

// --- GitHub Pages helpers ----------------------------------------------------
fs.writeFileSync(path.join(dist, '.nojekyll'), '');
fs.copyFileSync(indexPath, path.join(dist, '404.html')); // SPA fallback

console.log(`PWA post-process complete (base="${BASE || '/'}", ${precache.length} files precached).`);
